DefaultContentLanguage = "en"
author = "BAARMC"
baseURL = "http://baarmc.com.br"
copyright = "Copyright © BAARMC (CC BY-NC-SA 4.0)"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
languageCode = "en"
paginate = 3
theme = "github.com/jonathanjanssens/hugo-casper3"
title = "BAARMC"
[params]
description = "Brigada Autônoma Ambiental  da RMC"
facebook = "https://www.facebook.com/Baarmc-104247212224750"
github = "https://github.com/baarmc"
logo = ""
mainSections = ["test", "post"]
twitter = "https://twitter.com/brigadarmc"
[privacy.instagram]
disabled = true
simple = true
[privacy.twitter]
disabled = false
enableDNT = true
simple = true
[privacy.vimeo]
disabled = false
simple = true
[privacy.youtube]
disabled = false
privacyEnhanced = true
[services.instagram]
disableInlineCSS = false
[services.twitter]
disableInlineCSS = false
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
