DefaultContentLanguage = "en"
author = "BAARMC"
baseURL = "https://baarmc.com.br"
copyright = "Copyright © BAARMC (CC BY-NC-SA 4.0)"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
languageCode = "en"
paginate = 3
theme = "github.com/jonathanjanssens/hugo-casper3"
title = "BAARMC"
[[menu.main]]
identifier = "github-repo-theme"
name = "Get Theme on Github"
url = "https://github.com/jonathanjanssens/hugo-casper3"
weight = 30
[[menu.main]]
identifier = "author"
name = "Author Homepage"
url = "https://jonathanjanssens.com"
weight = 40
[params]
description = "Brigada Ambiental Autônoma da RMC"
facebook = "https://facebook.com"
github = "https://github.com/baarmc"
logo = ""
mainSections = ["post"]
twitter = "https://twitter.com"
[privacy.instagram]
disabled = false
simple = true
[privacy.twitter]
disabled = false
enableDNT = true
simple = true
[privacy.vimeo]
disabled = false
simple = true
[privacy.youtube]
disabled = false
privacyEnhanced = true
[services.instagram]
disableInlineCSS = true
[services.twitter]
disableInlineCSS = true
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
